name: Build and push to Azure Container Registry and deploy to Azure Container App

on:
  push:
    branches:
      - release/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Extract release version and Set to variable
        id: release_version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -E 's/^refs\/heads\/release\/(.*)$/\1/')
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZ_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZ_ACR_USERNAME }}
          password: ${{ secrets.AZ_ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/Feedback.Analyzer.Backend
          file: ./src/Feedback.Analyzer.Backend/Feedback.Analyzer.Api/Dockerfile
          tags: ${{ secrets.AZ_ACR_LOGIN_SERVER }}/insightboxbackend:${{ env.IMAGE_VERSION }}
          push: true
