name: Build and push InsightBox frontend to Azure Container Registry and deploy to Azure Container App

on:
  push:
    branches:
      - release/**
    paths:
      - ./.github/workflows/FrontendDeployToRelease
      - ./src/Insight.Box.FrontEnd/**
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Extract release version and Set to variable
        id: release_version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -E 's/^refs\/heads\/release\/(.*)$/\1/')
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZ_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZ_ACR_USERNAME }}
          password: ${{ secrets.AZ_ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/Insight.Box.FrontEnd
          file: ./src/Insight.Box.FrontEnd/Dockerfile
          tags: ${{ secrets.AZ_ACR_LOGIN_SERVER }}/insightboxfrontend:${{ env.IMAGE_VERSION }}
          push: true

  deploy-container-app:
    needs: build-and-push
    runs-on: ubuntu-latest
  
    steps:
      - name: Log in to Azure Container App
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_SP_CREDENTIALS }}

      - name: Extract release version and Set to variable
        id: release_version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -E 's/^refs\/heads\/release\/(.*)$/\1/')
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV
  
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ secrets.AZ_ACR_NAME }}
          containerAppName: ${{ secrets.AZ_FRONTEND_ACA_NAME }}
          resourceGroup: ${{ secrets.AZ_RG_NAME }}
          imageToDeploy: ${{ secrets.AZ_ACR_LOGIN_SERVER }}/insightboxfrontend:${{ env.IMAGE_VERSION }}
